### ISSUE TITLE
Bug - New vHack api ?

### ISSUE THREAD

**Issue by GodLea** [MrSonicMaster/vHackXT-MoneyBot#15]
Moneybot dont work
Kev released a new api?

![immagine](https://cloud.githubusercontent.com/assets/26212222/25185303/4e86001e-251d-11e7-8980-62a8e159d256.png)

**Comment by GodLea** [comment]
Now the bot its work. 
The dev has testing sametings

**Comment by MrSonicMaster** [comment]
Okay, if everything works good then close the issue.

**Comment by GodLea** [comment]
okkay sorry for the issue 
But be on the alert, the moneybot and a nice bot and I hope you keep on being active

**Comment by Tsm020** [comment]
MrSonicMaster

Any fix on the php500 error?

**Comment by GodLea** [comment]
New Api released
