### ISSUE TITLE
Problem with API

### ISSUE THREAD

**Issue by Kocmouch** [MrSonicMaster/vHackXT-MoneyBot#16]
Hello. I downloaded this script, as I want to check it out ^^

But I have a problem with launching It...

Client 0: Starting login...
Client 0: Fatal error: Failed to parse JSON. Invalid API response, outdated API version?
Press any key to continue . . .

Could You please help me?

**Comment by MrSonicMaster** [comment]
Yes, as it says "outdated API version." I have neglected to update the bot to function on the latest version of vHack-XT. I apologize, and I will attempt to update it asap.

**Comment by MrSonicMaster** [comment]
Closing issue for now.

**Comment by HybridFox** [comment]
Changing api version to 7 seems to work.
But again then i'm having the same issue as https://github.com/MrSonicMaster/vHackXT-MoneyBot/issues/14
