### ISSUE TITLE
[Suggestion] Change OCR implemetation to tesseract.js

### ISSUE THREAD

**Issue by ghost** [MrSonicMaster/vHackXT-MoneyBot#3]
HI,

what did you think about node-tesseract for OCR part in moneybot?

Maybe better for the known issue here: 

```
    imageToText(image, onfinish) { // Not always perfect, but is close enough.
        request(`https://megascouts.ml/ocr.php?png=${image}`, (err, res, body) => {
            if (err || res.statusCode !== 200) return onfinish(`Fatal error: Status code is ${res.statusCode}.`);
            onfinish(body);
        });
    }
```
Best :)

**Comment by MrSonicMaster** [comment]
The NPM module 'node-tesseract' requires the user to download a program to their computer to use it. My implementation uses TESSERACT download on my VPS/server (megascouts.ml), the PHP script is just a wrapper that creates a temporary file, runs tesseract-ocr on it, and echo's the output, then deletes the temporary file off my VPS/server. It is just another way where the user doesn't have to download anything else for this script to run correctly.
