### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by darkdragon2242** [MrSonicMaster/vHackXT-MoneyBot#7]
This is all it is doing, after having several login issues, I am now stuck with a non functional bot that just says Get new player list.
![9b7d0f8ef7ad4ae79084c08fc58cd908](https://cloud.githubusercontent.com/assets/26208184/23592078/19387bbe-01c1-11e7-95f6-79931043968e.png)

**Comment by MrSonicMaster** [comment]
I can confirm the bot still works, can you try running it on debug level 4 (go into the vHack.js file, and look for this.debugLevel = 0 and change the 0 to a 4) and pastebin me the logs (removing personal information of course.) I have seen others that see this low success rate as well, I will try to get this fixed right away.

**Comment by darkdragon2242** [comment]
For this issue after I ran in debug level 4 it worked just fine, not sure what the issue was.

**Comment by MrSonicMaster** [comment]
Hmm okay
