### ISSUE TITLE
why does the bot stop alone... ??

### ISSUE THREAD

**Issue by someonewhoplayvhack** [MrSonicMaster/vHackXT-MoneyBot#8]
all is explain.
![capture](https://cloud.githubusercontent.com/assets/26185813/23670754/145eabc8-0369-11e7-908f-17b2cf3da649.PNG)

**Comment by MrSonicMaster** [comment]
This is a known bug, I will fix this in the next update to the bot. Thanks for reporting it.

**Comment by someonewhoplayvhack** [comment]
thank you :)

**Comment by MrSonicMaster** [comment]
Bug fixed.
